baseURL = "http://codecode.club"
languageCode = "en-us"
title = "CodeCode Club"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "CodeCodeClub"
  homepage = "http://codecode.club"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "简体中文"
    weight = 2

[permalinks]
    post = "/blog/:title/"

[params]
lazyImage = true
headTitle = "CodeCode Club"
description = "代码只道寻常"
favicon = "/favicon.ico"
mainSections = ["posts"]
staticPrefix = ""
postHeaderContent = ""
postFooterContent = ""


[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about"
